- name: Set fact if OS family is Debian
  tags: always
  ansible.builtin.set_fact:
    is_debian_family: "{{ ansible_facts.os_family == \"Debian\" }}"

- name: Set fact if OS family is Darwin
  tags: always
  ansible.builtin.set_fact:
    is_darwin_family: "{{ ansible_facts.os_family == \"Darwin\" }}"

- name: Check gh authentication status
  tags: always
  ansible.builtin.command: gh auth status
  register: pre_flight_checks_gh_auth_status
  changed_when: false
  failed_when: false

- name: Set fact if gh CLI is not authenticated # noqa: var-naming[no-role-prefix]
  tags: always
  ansible.builtin.set_fact:
    is_gh_cli_not_authenticated: "{{ pre_flight_checks_gh_auth_status.rc != 0 }}"

- name: Fail if gh CLI is not authenticated
  tags: always
  ansible.builtin.fail:
    msg: |
      gh CLI is not authenticated. This process is automated in the 'install.sh' script.
      Please run 'install.sh' or manually run 'gh auth login' before running this playbook.
  when: is_gh_cli_not_authenticated

- name: Get gh CLI version
  tags: always
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gh --version | head -n 1 | cut -d ' ' -f 3
    executable: /bin/bash
  register: pre_flight_checks_gh_version
  changed_when: false
  failed_when: false

- name: Set gh CLI version fact
  tags: always
  ansible.builtin.set_fact:
    pre_flight_checks_gh_version_number: "{{ pre_flight_checks_gh_version.stdout | trim }}"

- name: Check for required gh auth scopes
  tags: always
  ansible.builtin.fail:
    msg: |
      The 'gh' command is not authenticated with the required scopes.
      Please run the following command to grant the necessary permissions:
      gh auth refresh -h github.com -s admin:public_key,admin:gpg_key
  when:
    - not is_gh_cli_not_authenticated
    - pre_flight_checks_gh_version is defined
    - pre_flight_checks_gh_version_number is version('2.48.0', '>=')
    - "'admin:public_key' not in pre_flight_checks_gh_auth_status.stdout or 'admin:gpg_key' not in pre_flight_checks_gh_auth_status.stdout"

- name: Install ssh-askpass for Debian
  tags: always
  ansible.builtin.package:
    name: ssh-askpass
    state: present
  when: is_debian_family
  become: true

- name: Install openssh for macOS
  tags: always
  community.general.homebrew:
    name: openssh
    state: present
  when: is_darwin_family

- name: Check for administrative privileges on Windows
  tags: always
  when: is_windows
  block:
    - name: Check if the current user is an Administrator # noqa: var-naming[no-role-prefix]
      ansible.builtin.command:
        cmd: >
          powershell.exe -Command "([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)"
      register: admin_check_ps
      changed_when: false
      failed_when: false

    - name: Set has_admin_privileges fact # noqa: var-naming[no-role-prefix]
      ansible.builtin.set_fact:
        has_admin_privileges: "{{ admin_check_ps.stdout | trim == 'True' }}"
