- name: Install MCP tools (macOS)
  ansible.builtin.include_tasks: macos.yml
  when: is_mac

- name: Install MCP tools (Linux)
  ansible.builtin.include_tasks: linux.yml
  when: is_debian_family

- name: Install MCP tools (Windows)
  ansible.builtin.include_tasks: windows.yml
  when: is_windows

- name: Set pnpm executable path (Windows)
  when: is_windows
  block:
    - name: Get user's home directory path in POSIX format
      ansible.builtin.command:
        cmd: cygpath -u "{{ ansible_facts['env']['USERPROFILE'] }}"
      register: configure_mcp_win_home_dir
      changed_when: false

    - name: Set pnpm executable fact
      ansible.builtin.set_fact:
        configure_mcp_pnpm_executable: "{{ configure_mcp_win_home_dir.stdout }}/AppData/Local/pnpm/pnpm"
        configure_mcp_nodejs_path: "{{ configure_mcp_win_home_dir.stdout }}/scoop/persist/nvm/nodejs/nodejs"

- name: Configure MCP servers (JSON)
  ansible.builtin.include_tasks: configure_mcp.yml

- name: Configure Gemini Extensions
  ansible.builtin.include_tasks: configure_extensions.yml
