- name: Setup Ansible Controller
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install required packages
      become: true
      apt:
        name:
          - python3-pip
          - bash-completion
        state: present
        update-cache: true

    - name: Install argcomplete for Ansible Bash Completion
      pip:
        name:
          - argcomplete
        state: present
        extra_args: --user

    - name: Activate global argcomplete 
      shell: activate-global-python-argcomplete3 --user
      args:
        executable: /bin/bash
