- name: Install + Configure SpaceVim
  hosts: localhost
  connection: local
  gather_facts: true
  pre_tasks:
    - include_tasks: ../common/set_os_facts.yml
  tasks:
    - name: Set OS specific facts
      when: is_windows
      set_fact:
        minttyrc_file: >-
          {{ '/c/Users/' + ansible_user_id + '/.minttyrc'
          if is_windows 
          else '~/.minttyrc' }}

    - name: Set general facts
      set_fact:
        spacevim_config_dir: >-
          {{ '/c/Users/' + ansible_user_id + '/.SpaceVim.d'
          if is_windows 
          else '~/.SpaceVim.d' }}

    - name: Ensure required dependencies are installed
      block:
        - name: Ensure Debian-based system dependencies are installed
          when: is_debian_family
          become: true
          apt:
            name: tar
            state: present
            update_cache: yes

        - name: Ensure MacOS dependencies are installed
          when: is_mac
          block:
            - name: Check if Homebrew is installed
              command: brew -v
              register: brew_check
              ignore_errors: yes

            - name: Fail if Homebrew is not installed
              fail:
                msg: 'Homebrew is not installed. Please install Homebrew first.'
              when: brew_check.rc != 0

        - name: Ensure Windows dependencies are installed
          when: is_windows
          block:
            - name: Check if MSYS2 is installed on Windows
              stat:
                path: "{{ item }}"
              loop:
                - '/c/msys64/mingw64.exe'
                - '/c/tools/msys64/mingw64.exe'
              register: msys2_check

            - name: Fail if MSYS2 is not installed on Windows
              when:
                - msys2_check.results | selectattr('stat.exists', 'equalto', false) | list | length == msys2_check.results | length
              fail:
                msg: 'MSYS2 is not installed. Please install MSYS2 before running this playbook.'

            - name: Check if Chocolatey is installed
              win_shell: choco -v
              register: choco_check
              ignore_errors: yes

            - name: Fail if Chocolatey is not installed
              fail:
                msg: 'Chocolatey is not installed. Please install Chocolatey first.'
              when: choco_check.rc != 0

    - name: Install SpaceVim
      block:
        - name: Download SpaceVim install.sh
          get_url:
            url: https://spacevim.org/install.sh
            dest: /tmp/install_spacevim.sh
            mode: '0755'

        - name: Install SpaceVim
          command: bash /tmp/install_spacevim.sh
          args:
            creates: "{{ spacevim_config_dir }}"

        - name: Remove install_spacevim.sh
          file:
            path: /tmp/install_spacevim.sh
            state: absent

    - name: Install Nerd Font
      block:
        - name: Install Nerd Font on Windows 
          when: is_windows
          shell: choco install cascadia-code-nerd-font -y

        - name: Install Nerd Font on MacOS
          when: is_mac
          homebrew_cask:
            name: font-caskaydia-cove-nerd-font
            state: present

        - name: Install Nerd Font on Debian
          when: is_debian_family
          block:
            - name: Install Nerd Font (Debian)
              check_mode: false
              get_url:
                url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/CascadiaCode.tar.xz
                dest: '/tmp/CascadiaCode.tar.gz'
              register: download

            - name: Unarchive font
              when: download.changed
              unarchive:
                src: '/tmp/CascadiaCode.tar.gz'
                dest: '~/.local/share/fonts/'
                remote_src: yes

            - name: Update font cache
              when: download.changed
              command: fc-cache -fv
              args:
                warn: false

    - name: Configure MINTTY to use Nerd Font on Windows
      when: is_windows
      block:
        - name: Ensure .minttyrc file exists
          file:
            path: "{{ minttyrc_file }}"
            state: touch

        - name: Update .minttyrc to use Nerd Font
          lineinfile:
            path: "{{ minttyrc_file }}"
            regexp: '^Font='
            line: 'Font=CaskaydiaCove Nerd Font'

    - name: Configure SpaceVim
      block:
        - name: Ensure .SpaceVim.d directory exists
          file:
            path: "{{ spacevim_config_dir }}"
            state: directory

        - name: Ensure init.toml file exists
          file:
            path: "{{ spacevim_config_dir }}/init.toml"
            state: touch

        - name: Add custom_plugins header to SpaceVim configuration
          lineinfile:
            path: "{{ spacevim_config_dir }}/init.toml"
            line: '[[custom_plugins]]'

        - name: Add custom SpaceVim plugins
          blockinfile:
            path: "{{ spacevim_config_dir }}/init.toml"
            insertafter: '^\[\[custom_plugins\]\]$'
            block: |
              repo = 'github/copilot.vim'
              merged = false

              [[custom_plugins]]
              repo = 'dracula/vim'
              merged = false

              [[custom_plugins]]
              repo = 'pearofducks/ansible-vim'
              merged = false
            marker: '# {mark}: ANSIBLE MANAGED CUSTOM PLUGINS'

        - name: Add options header to SpaceVim configuration
          lineinfile:
            path: "{{ spacevim_config_dir }}/init.toml"
            line: '[options]'

        - name: Configure SpaceVim init.toml
          blockinfile:
            path: "{{ spacevim_config_dir }}/init.toml"
            insertafter: '^\[options\]$'
            block: |
              colorscheme = 'dracula'
              colorscheme_bg = 'dark'
              # NOTE: Disable guicolors in basic mode, many terminals do not support 24bit true colors.
              enable_guicolors = {{ 'false' if is_mac else 'true' }}
              statusline_separator = 'arrow'
              statusline_iseparator = 'arrow'
              buffer_index_type = 0
              enable_tabline_filetype_icon = true
              enable_statusline_mode = true
              bootstrap_after = 'myspacevim#after'

              [[layers]]
              name = 'autocomplete'
              auto-completion-return-key-behavior = 'complete'
              auto-completion-tab-key-behavior = 'cycle'

              [[layers]]
              name = 'shell'
              default_position = 'top'
              default_height = 50

              [[layers]]
              name = 'telescope'
            marker: '# {mark}: ANSIBLE MANAGED OPTIONS'

        - name: Ensure autoload directory exists
          file:
            path: "{{ spacevim_config_dir }}/autoload"
            state: directory
            mode: '0755'

        - name: Copy bootstrap functions to autoload directory
          copy:
            src: ../config/spacevim/autoload/myspacevim.vim
            dest: "{{ spacevim_config_dir }}/autoload/myspacevim.vim"
            mode: '0644'
